#! /usr/bin/php
<?php

function dump_sql($tableArray, $tableName)
{
    $outputQuery = "INSERT INTO $tableName VALUES (";
    foreach($tableArray as $value)
    {
        $tmp = mysql_real_escape_string($value);
        $outputQuery .= "'$tmp',";
    }
    return substr($outputQuery,0,strlen($outputQuery)-1) . ");";
}

function dump_sql_rows($query, $tableName)
{
    $queryOutput = "";
    $queryRows = mysql_query($query) or die("Query error:" . mysql_error() . "\n");
    while($queryRow = mysql_fetch_row($queryRows))
    {
        $queryOutput .= dump_sql($queryRow, $tableName) . "\n";
    }
    return $queryOutput;
}

// Change your database settings here:
$db = mysql_connect("localhost", "planeshift", "planeshift") or die ("Unable to connect!"); // host, user, pass
mysql_select_db("planeshift", $db) or die("Could not select database");

$accountID = 0;

if($argc < 2)
{
    die("You need to specify an account id or username (usually the email)\n");
}

if(!is_numeric($argv[1]))
{
    //search by username
    $accountID_query = mysql_query("SELECT id FROM accounts WHERE username = '$argv[1]'") 
                                   or die ("Query error:" . mysql_error() . "\n");

    if(mysql_num_rows($accountID_query) == 0)
        die("Account ".$argv[1]." not Found!\n");
        
    $accountID = mysql_result($accountID_query, 0, "id");
}
else
{
    $accountID = $argv[1];
}
$account_query = mysql_query("SELECT * FROM accounts WHERE id = '$accountID'") or die ("Query error:" . mysql_error() . "\n");

if(mysql_num_rows($account_query) == 0)
    die("Account ".$argv[1]." not Found!\n");

$accountData = mysql_fetch_row($account_query);
echo "\n---------------- CUT HERE -----------------------\n\n";

$accountQueryOutput = dump_sql($accountData, "accounts") . "\n\n";

echo $accountQueryOutput;
    
$charactersRows = mysql_query("SELECT * FROM characters WHERE account_id = '$accountID'") or die("Query error:" . mysql_error() . "\n");

if(mysql_num_rows($charactersRows) == 0)
    die("Account ".$argv[1]." has no characters!\n");
    
while($characterRow = mysql_fetch_row($charactersRows))
{
    $characterID = $characterRow[0];
    $charactersQueryOutput = "\n\n" . dump_sql($characterRow, "characters") . "\n\n";
    echo $charactersQueryOutput;
    
    //dump character quests
    printf(dump_sql_rows("SELECT * FROM character_quests where player_id = '$characterID'", "character_quests"));
    //dump character skills
    printf(dump_sql_rows("SELECT * FROM character_skills where character_id = '$characterID'", "character_skills"));
    //dump character traits
    printf(dump_sql_rows("SELECT * FROM character_traits where character_id = '$characterID'", "character_traits"));
    //dump player spells
    printf(dump_sql_rows("SELECT * FROM player_spells where player_id = '$characterID'", "player_spells"));
    //dump items
    printf(dump_sql_rows("SELECT * FROM item_instances where char_id_owner = '$characterID'", "item_instances"));
}

?>
