// This file is automatically generated.
#include "cssysdef.h"

struct CS_IMPORT_SYM _Bind_psserver_static_plugins_LIBMYSQLCLIENT
{
  _Bind_psserver_static_plugins_LIBMYSQLCLIENT ();
};
namespace { _Bind_psserver_static_plugins_LIBMYSQLCLIENT bind_psserver_static_plugins_LIBMYSQLCLIENT; }

