#! /usr/bin/php
<?php
// Converter for loot modifiers - assumes DB schema has already been updated to 1214
// (or at least prg_evt_equip has been renamed to equip_script).

// Change your database settings here:
$db = mysql_connect("localhost", "planeshift", "planeshift") or die ("Unable to connect!"); // host, user, pass
mysql_select_db("planeshift", $db) or die("Could not select database");

$scripts = mysql_query("SELECT * from common_strings") or die("fatal error: couldn't select stuff: " . mysql_error() . "\n");
while ($row = mysql_fetch_array($scripts))
{
    if(preg_match('!/planeshift/models/$F/$F.*dds!', $row['string']))
    {
       $s = mysql_real_escape_string(replace('.dds','',replace('/planeshift/models/$F/', '', $row['string'])));
    }
    else
    {
	$s = mysql_real_escape_string(preg_replace('!/planeshift/.*/!', '/planeshift/materials/', $row['string']));
    }
    echo "Updating " . $row['string'] . "...\n";
    mysql_query("UPDATE common_strings SET string = '$s' WHERE id=" . $row['id']) or die(mysql_error() . "\n");
}

?>
